name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: Package
      shell: bash
      run: |
        subversion=`date +%Y%m%d`
        echo $subversion
        dotnet pack src/InfluxDb.Extensions -o . -c Release -p:PackageVersion=1.0.5-CI-$subversion
    - name: push nuget
      run:
        dotnet nuget push *.nupkg -k ${{secrets.nuget_apikey}} -s https://api.nuget.org/v3/index.json

